courses/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.course_list),
    url(r'(?P<course_pk>\d+)/(?P<step_pk>\d+)$', views.step_detail),
    url(r'(?P<pk>\d+)$', views.course_details),
]

learning_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'courses/', include('courses.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.hello_world),
]

urlpatterns += staticfiles_urlpatterns()

courses/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title


class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    content = models.TextField(blank=True, default='')
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    class Meta:
        ordering = ['order', ]

    def __str__(self):
        return self.title

courses/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404

from .models import Course, Step
# Create your views here.


def course_list(request):
    courses = Course.objects.all()
    return render(request, 'courses/course_list.html', {'courses': courses})


def course_details(request, pk):
    course = get_object_or_404(Course, pk=pk)
    return render(request, 'courses/course_detail.html', {'course': course})


def step_detail(request, course_pk, step_pk):
    step = get_object_or_404(Step, course_id=course_pk, pk=step_pk)
    return render(request, 'courses/step_detail.html', {'step': step})

learning_site/views.py
from django.shortcuts import render


def hello_world(request):
    return render(request, 'home.html')

courses/templates/courses/course_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ course.title }}</title>
</head>
<body>
    {% for step in course.step_set.all %}
        <h3>{{ step.title }}</h3>
        <p>{{ step.description }}</p>
    {% endfor %}
</body>
</html>

courses/templates/courses/course_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Courses</title>
</head>
<body>
{% for course in courses %}
<h2>{{course.title}}</h2>
{{course.description}}
{% endfor %}
</body>
</html>

courses/templates/courses/step_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ step.course.title }}</title>
</head>
<body>
    <h3>{{step.title }}</h3>
    <p>{{ step.description }}</p>
</body>
</html>

templates/home.html
{% load static from staticfiles%}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    <title>Home</title>
</head>
<body>
<h1 class="site-container">Welcome!</h1>
</body>
</html>